### ISSUE TITLE
Implement custom matcher to make tests more expressive

### ISSUE THREAD

**Issue by joshuajmurray** [JolliestJames/brewtiful#10]

**Comment by JolliestJames** [comment]
https://github.com/JolliestJames/brewtiful/commit/4123bcb0cbddc88d8c9aa6e5938092bfa87fabde and https://github.com/JolliestJames/brewtiful/commit/5ae3c0139221c79625a454175ebad354a782a88f reference this

**Comment by JolliestJames** [comment]
https://github.com/JolliestJames/brewtiful/commit/a0322ed8d5a2ff634fcd0f781b11e81cfeded251 references this
